Support for cross filesystem restore/backup
Useful when using docker and mounting the config dir which is on the host as a data volume.
Else it fails with :
Traceback (most recent call last):
  File "/opt/hydra/nzbhydra/backup_debug.py", line 127, in restoreFromBackupData
    os.rename(databaseTempFile, nzbhydra.databaseFile)
OSError: [Errno 18] Cross-device link