fix key error for when a forgidden regex was found
Fixed a spelling error that caused the KeyError.

```
2017-02-17 02:28:06,313 - ERROR - search_module - Thread-137 - Oznzb: Error while processing search results from indexer Oznzb
Traceback (most recent call last):
  File "/root/nzbhydra/nzbhydra/search_module.py", line 425, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/root/nzbhydra/nzbhydra/searchmodules/newznab.py", line 506, in process_query_result
    countRejected[ri] += 1
KeyError: u'the forbidden regex was found in the title'
2017-02-17 02:28:06,315 - ERROR - search_module - Thread-137 - Oznzb: Access error: Error while parsing the results from indexer
```